// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfdtgrzmnqfzgsdzwygs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZHRncnptbnFmemdzZHp3eWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTUwMDQsImV4cCI6MjA2MDY3MTAwNH0.cL6sxvvA4wLwEiCXBSKJnIr6eWNaVtE_DtDI4PQSBm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);